


GET http://localhost:8080/api/pizza/1

###

POST http://localhost:8080/api/pizza
Content-Type: application/json

{
  "crust": "garlic",
  "price": 29.99,
  "toppings": "pepperoni",
  "hasCheese": true,
  "size": "large"
}

###

GET http://localhost:8080/api/pizza?id=1

###

GET http://localhost:8080/api/pizza