CREATE TABLE pizza
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    crust      VARCHAR(255),
    price      DOUBLE PRECISION,
    size       VARCHAR(255),
    toppings   VARCHAR(255),
    has_cheese BOOLEAN,
    CONSTRAINT pk_pizza PRIMARY KEY (id)
);